### ISSUE TITLE
Introduce alias to `<sqlCheck>`

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquibase-neo4j#146]
This should be fairly similar to what's been done with the `<cypher>` alias to `<sql>` (see the [CypherChange](https://github.com/liquibase/liquibase-neo4j/blob/main/src/main/java/liquibase/ext/neo4j/change/CypherChange.java) class).

Here, the idea would be to subclass `liquibase.precondition.core.SqlPrecondition` in the `precondition` package of the plugin, and just override `public String getName()` to return `"cypherCheck"`.

This new subclass must be declared in the `META-INF/services/liquibase.precondition.Precondition` file.

**Comment by clarenced** [comment]
I want to work on this issue. Can I help ?

**Comment by fbiville** [comment]
Perfect, let me know if you need any help!

**Comment by clarenced** [comment]
Is the alias is `sqlCheck` or `cypherCheck` ?
