### ISSUE TITLE
JHipster support - Phase 1 - `<loadData>`

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquibase-neo4j#148]
Note: this is required for #38.

JHipster generated migrations inserts users, authorities and assigns authorities to users.
This is done with `<loadData>` (to get the data from flat CSV files) and `<addForeignKeyConstraint>` (for the user<-->authority join).

```xml
        <addForeignKeyConstraint baseColumnNames="authority_name"
                                 baseTableName="jhi_user_authority"
                                 constraintName="fk_authority_name"
                                 referencedColumnNames="name"
                                 referencedTableName="jhi_authority"/>

        <addForeignKeyConstraint baseColumnNames="user_id"
                                 baseTableName="jhi_user_authority"
                                 constraintName="fk_user_id"
                                 referencedColumnNames="id"
                                 referencedTableName="jhi_user"/>

        <loadData
                  file="config/liquibase/data/user.csv"
                  separator=";"
                  tableName="jhi_user"
                  usePreparedStatements="true">
            <column name="activated" type="boolean"/>
            <column name="created_date" type="timestamp"/>
        </loadData>
        <loadData
                  file="config/liquibase/data/authority.csv"
                  separator=";"
                  tableName="jhi_authority"
                  usePreparedStatements="true">
            <column name="name" type="string"/>
        </loadData>
        <loadData
                  file="config/liquibase/data/user_authority.csv"
                  separator=";"
                  tableName="jhi_user_authority"
                  usePreparedStatements="true">
            <column name="user_id" type="string"/>
        </loadData>
```

Discussing this with @conker84, we came up with two different ideas.

## "Dumb" `<loadData>` strategy

Each `<loadData>` change results in nodes being inserted. 

 - `tableName` maps to a node label
 -  property names are either derived from the loaded file or from the inner `<column>` configs (the core logic already handles this).

When we encounter `<addForeignKeyConstraint>` changes, we track the mapping in memory.
In particular: 
 - `baseTableName` is the label of the "source" nodes
 - `baseColumnNames` are the property names of the "source" nodes involved in the equality
 - `referencedTableName` is the label of the "destination" nodes
 - `referencedColumnNames` are the property names of the "destination" nodes involved in the equality
 - `constraintName` is the name of the relationship that will be created between each matching "source" and "destination" nodes

Once the migrations are done running (when `liquibase.changelog.ChangeLogHistoryService#destroy` is called?), then we match every "source" and "destination" based on the tracked foreign key changes and link them together.

## Smart `<loadData>` strategy

This slightly varies from the previous approach.

`<loadData>` could behave in two ways:

 1. if its `tableName` attribute matches the `baseTableName` of a  `<addForeignKeyConstraint>` change, `<loadData>` will  create relationships, not nodes. The relationship property names are derived from either the CSV file or `<column>` setting.
 2. else, it will work as described in the previous section

The tracking of `<addForeignKeyConstraint>` would only be necessary for `<loadData>` executions, so we would not need to execute anything at the end of all migrations (like the first approach describes).

**Comment by michael-simons** [comment]
What you describe as the dumb solution is the smart solution.  In relational a foreign key is just a constraint in graph it’s an entity on its own right defined by the unique identifiers of both ends. 

In relational there are no properties on the foreign key. You would need an intersection table for that, basically a 3rd node having the props. 

Wrt drop: you would - if u following a sane logic - drop all the relationships of that type as derived from the constraint name before.

**Comment by fbiville** [comment]
After many discussions with @conker4 and @nvoxland, I think the fastest way forward is to initially just support `<loadData>` and add an extra change set, that will explicitly create the relationships.
This extra change set can be guarded with a precondition `<dbms name="neo4j" />` or a template condition (or both).

The `<addForeignKeyConstraint />` support, if it ever comes, will be handled later, I'll open a new issue for that.
