### ISSUE TITLE
Configure Dependabot for GitHub actions updates

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquibase-neo4j#149]
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

**Comment by RishiKumarRay** [comment]
I would like to give a try for this

**Comment by fbiville** [comment]
@RishiKumarRay please do.
You'll need to edit https://github.com/liquibase/liquibase-neo4j/blob/main/.github/dependabot.yml and add the necessary configuration for GitHub actions as explained in the link above.

**Comment by fbiville** [comment]
@RishiKumarRay is there anything I can help with? I'd love to see this issue solved.
