### ISSUE TITLE
Will liquibase-neo4j have release and be published?

### ISSUE THREAD

**Issue by gpanda70** [liquibase/liquibase-neo4j#15]
Hi team,

Is there going to be a release for this project anytime soon and will that release be pushed to repo.maven.apache.org? My team was interested in using liquibase-neo4j for our neo4j DB. 

I see that other liquibase extensions like liquibase-redshift are in https://repo.maven.apache.org/maven2/org/liquibase/ext/
but not this project

Thanks!

**Comment by fbiville** [comment]
Hi, thanks for the kind words.
I'll let you know ASAP. This will hopefully happen soon.

**Comment by fbiville** [comment]
It is released as of yesterday: https://search.maven.org/search?q=liquibase-neo4j thanks to @r2liquibase!
Enjoy :)
