### ISSUE TITLE
Liquibase Database CLI input

### ISSUE THREAD

**Issue by dtendo** [liquibase/liquibase-neo4j#150]
Is there a way to specify a database in the cli?

**Comment by fbiville** [comment]
Hello, that's great question and I think I should update the `README` to be more explicit about this.
The database can be specified in the JDBC connection URI: https://github.com/neo4j-contrib/neo4j-jdbc#list-of-supported-neo4j-configuration-parameters.

**Comment by fbiville** [comment]
@dtendo please let me know what you think of https://github.com/liquibase/liquibase-neo4j/pull/151?

**Comment by dtendo** [comment]
Thanks. The connection uri works. with zsh, I need to wrap it in single quotes but that's all.
'jdbc:neo4j:bolt://localhost?database=myDb'
