### ISSUE TITLE
Liquibase condition check scheduler thread blocks shutdown

### ISSUE THREAD

**Issue by pelletier197** [liquibase/liquibase-neo4j#186]
I didn't know how to name that issue, but it says what is happening. I had a weird issue that my application was not shutting down even though the migrations were completed. After a long investigation, I found out that it was because of the liquibase plugin, and more precisely because of the Neo4j liquibase's `ConditionCheckScheduler` class. 

Basically, this class creates a `ScheduledExecutorService` like this

```java
public ConditionCheckScheduler(Duration timeout) {
    this.scheduledExecutorService = Executors.newScheduledThreadPool(1);
    this.timeout = timeout;
}
```

This way of creating the thread pool adds `core threads`, which are non-daemon and will stop the application from shutting down. According to this [stackoverflow answer](https://stackoverflow.com/questions/34202701/how-to-stop-a-scheduledexecutorservice), there are two ways to fix this. 

1. Either put core pool size to 0, so all threads created will be daemon.
2. Shutdown the executor after you're done using it. 

Probably in your case, doing both would be the best thing to do?

Thanks a lot for this plugin by the way, really great!

**Comment by fbiville** [comment]
Hello, what version of the underlying Neo4j Java Driver are you using?
The daemon thread issue has been fixed recently(-ish)?

**Comment by fbiville** [comment]
Could you try this fix by any chance @pelletier197? https://github.com/liquibase/liquibase-neo4j/pull/187

**Comment by pelletier197** [comment]
Yes, for sure. Does this create a snapshot library I can import?

**Comment by fbiville** [comment]
I can at least manually upload a SNAPSHOT for you if that helps.

**Comment by pelletier197** [comment]
If it's not too complicated, that would be faster for me. Otherwise, I can try to find a way later today.

**Comment by fbiville** [comment]
Asking Liquibase folks, since I don't know the credentials for the SNAPSHOT upload.

If you've got Maven and Git installed, you can also run this one-liner:
```
cd $(mktemp -d) && git clone https://github.com/liquibase/liquibase-neo4j -b pool_closed && mvn --file liquibase-neo4j install -DskipTests
```
and set  your dependency version to `4.10.1-issue-186-SNAPSHOT`

**Comment by pelletier197** [comment]
Thanks for the one liner. This fixed my issue, my app now closes normally.

Thanks a lot!

**Comment by fbiville** [comment]
https://github.com/liquibase/liquibase-neo4j/releases/tag/liquibase-neo4j-4.10.1 is out, it should be available in a few hours.

**Comment by pelletier197** [comment]
> Thanks for the detailed report and apologies for the silly mistake in the first place

No problem, I would probably have done the same mistake tbh.

Thanks you again!
