### ISSUE TITLE
:memo: Please fill the about section :smile_cat: 

### ISSUE THREAD

**Issue by adriens** [liquibase/liquibase-neo4j#211]
Hi, this plugin is very very interesting :heavy_heart_exclamation: 

Would you consider complete the project description :grey_question: 

![image](https://user-images.githubusercontent.com/5235127/183778372-37eeaae1-3d2b-4996-8b15-7d4190dd86c9.png)

**Comment by fbiville** [comment]
Thanks, I reached out to our friends at Liquibase, I currently don't have the right to edit that section.

**Comment by molivasdat** [comment]
@adriens We updated it.
