### ISSUE TITLE
jar format no longer available in releases since 4.13

### ISSUE THREAD

**Issue by doakd** [liquibase/liquibase-neo4j#216]
Please provide jar format for releases again.  Makes it much harder for us to upgrade when only .zip and .gz are available.

**Comment by adriens** [comment]
:heavy_plus_sign: :one:  in the :ballot_box:

**Comment by fbiville** [comment]
Oh I know, what happened. I started to use JReleaser to populate change logs and it might have overwritten the uploaded JARs. I'll fix up the existing releases and fix JReleaser configuration.

For the time being, please note that the JARs are also available from Maven Central and they will always be there: https://repo.maven.apache.org/maven2/org/liquibase/ext/liquibase-neo4j/.

**Comment by fbiville** [comment]
See e.g. https://github.com/liquibase/liquibase-neo4j/releases/tag/liquibase-neo4j-4.15.0.1 that I just created and JReleaser has not run yet.

**Comment by doakd** [comment]
Maven Central is being blocked by our company firewall.  Can you add the jars for 4.14 also?

**Comment by fbiville** [comment]
Yes, will do ASAP @doakd

**Comment by fbiville** [comment]
Older releases have been manually fixed up, new releases won't have the problem, thanks to @aalmiray work.
