### ISSUE TITLE
Document `<loadData />` mappings

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquibase-neo4j#271]

**Comment by adriens** [comment]
Hi guys, any roadmap to get this higly awaited feature ?

**Comment by fbiville** [comment]
Hello, 

Sorry for the delay.

- Nascent Asciidoctor is currently in https://github.com/liquibase/liquibase-neo4j/pull/198. Just need to find some time to make includes work.
- JHipster is a bit in a limbo at the moment: https://github.com/jhipster/generator-jhipster/pull/17956
- `<loadData />` is fully supported since 4.16.1.1, need to add proper docs
- @mgazanayi and I barely started on the index/constraint changes, since it's quite a big surface to cover, with many variations across Neo4j versions
- a new refactoring called "node property extraction" has landed alongside the "merge nodes" one since 4.17.2, see: https://www.neo4j.com/labs/liquibase/docs/reference-custom-features/#node-property-extraction
- batch execution support will probably land soon enough, once https://github.com/liquibase/liquibase-neo4j/pull/288 is merged (see https://github.com/liquibase/liquibase-neo4j/releases/tag/liquibase-neo4j-jdbc-alpha-01)

Is there any particular feature you'd like to see first? At this time, priority is based on demand, you have a lot of power there :)

**Comment by adriens** [comment]
@fbiville : 

> <loadData /> is fully supported since 4.16.1.1, need to add proper docs

Awesome news :clap: just let me know when the doc is availlable and we'll start working on it. It will unlock one of our prjects :muscle: ... and save so much time :pray:

**Comment by fbiville** [comment]
@adriens the documentation is now live: https://www.neo4j.com/labs/liquibase/docs/reference-features/#load-data

**Comment by adriens** [comment]
Yes, I saw the releleasenote :clap: 

Here are some shortucts we'll use : 

- :gift:  [Quick Start](https://github.com/liquibase/liquibase-neo4j/blob/main/docs/quickstart.md)
- [Load data with the loadData tag](https://docs.liquibase.com/change-types/load-data.html)
- [Custom Features](https://github.com/liquibase/liquibase-neo4j/blob/main/docs/reference-features.md)
- [Neo4j Preconditions](https://github.com/liquibase/liquibase-neo4j/blob/main/docs/reference-features.md#neo4j-preconditions)
- [`loadData` doc complète](https://docs.liquibase.com/change-types/load-data.html)

Thanks to your work we'll be able to automate a lot of things.

Also, having a  [Quick Start](https://github.com/liquibase/liquibase-neo4j/blob/main/docs/quickstart.md)
 really is a good idea :pray: 

Thanks a lot for the great work, I'll let you know :-p

Have a nice week-end.

**Comment by fbiville** [comment]
Feel free to start [a discussion](https://github.com/liquibase/liquibase-neo4j/discussions) if you need help with something!

**Comment by adriens** [comment]
Sure, I'll be on holidays within the next weeks byt we will proably create a dedicated blog post for this feature :+1:
