### ISSUE TITLE
Update hanging with neo4j 5

### ISSUE THREAD

**Issue by borgoat** [liquibase/liquibase-neo4j#282]
I've been unsuccessfully trying to run the [quick start example](https://neo4j.com/labs/liquibase/docs/quickstart/
) from the docs on Neo4j 5 enterprise; both via Aura DB and locally with Docker (linux/arm64).

While this works on 4.4.14, on 5.1.0 it merely hangs.

I'm using the latest version of liquibase (4.17.2) and liquibase-neo4j: https://github.com/liquibase/liquibase-neo4j/releases/tag/liquibase-neo4j-4.17.2
and looking at #277 it seems initial support for v5 was implemented... not sure if I'm doing something wrong though. I'm not particularly familiar with neither Liquibase nor Neo4j. 🤷 

As an additional data point, I'm running liquibase from macOS 13, arm64, JDK 18.

Here is the configuration and debug logs for the 2 cases: https://gist.github.com/borgoat/07fe03a31fb48f7736d234e3a688fa33

I did test on the community edition too - but because the result is identical I did not add it to the logs.

**Comment by fbiville** [comment]
In the mean time, you can try building the `neo4j-jdbc-bolt` JAR from sources and see if that works for you:
```shell
git clone https://github.com/neo4j-contrib/neo4j-jdbc.git
mvn install --file neo4j-jdbc/pom.xml --also-make --projects neo4j-jdbc-bolt -DskipTests
```

Then add to your POM:
```xml
<dependency>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j-jdbc-bolt</artifactId>
        <version>5.1.0</version>
</dependency>
```

Once you're done, do not forget to remove the dependency from your local cache (`rm -r ~/.m2/repository/org/neo4j/neo4j-jdbc-bolt/5.1.0`)

**Comment by fbiville** [comment]
Alternatively @borgoat, can you try https://github.com/liquibase/liquibase-neo4j/releases/tag/liquibase-neo4j-jdbc-alpha-01 and report back?

**Comment by fbiville** [comment]
Hello @borgoat, can you try Liquibase Neo4j 4.19.0 and report back? This includes the new JDBC implementation and should fix all your issues.

**Comment by borgoat** [comment]
Thanks @fbiville - haven't had much time to look into it lately, I'll give it a shot in the coming days though!

**Comment by fbiville** [comment]
Hello @borgoat, have you had a chance to try out Liquibase Neo4j 4.19?

**Comment by fbiville** [comment]
Liquibase has been supporting Neo4j 5 for a while, please reopen the issue if the problem still occurs @borgoat.
