### ISSUE TITLE
Full JAR missing since 4.17.1 + 4.17.2.* missing from Maven Central

### ISSUE THREAD

**Issue by doakd** [liquibase/liquibase-neo4j#290]
liquibase-neo4j-4.17.2.1-full.jar is missing from releases.

**Comment by fbiville** [comment]
Hello, thanks for the report. I'll manually fix this for the time being.
I believe the problem started appearing since 4.17.1 when I switched to the new release workflow.
I'll let you know when the fix is done.

**Comment by fbiville** [comment]
I notified the Liquibase folks and added the full JAR for each affected GitHub release.
Will close this issue when the root cause is addressed.
