### ISSUE TITLE
Need help with migration of Liquigraph postconditions

### ISSUE THREAD

**Issue by andrewjroth** [liquibase/liquibase-neo4j#297]
Is it possible to convert a Liquigraph changelog XML to a Liquibase XML without using a live database?

We have several postconditions which include a query.  Could you please let us know how to convert this?

Thank you,
Andrew

**Comment by fbiville** [comment]
Hey @andrewjroth, thanks for the report (I somehow missed it before!).
Can you post the change set(s) with the post conditions?

**Comment by andrewjroth** [comment]
Do you have instructions on how to manually migrate?

**Comment by fbiville** [comment]
@andrewjroth would you be able to share the change sets here or by email (first name dot last name at neo4j dot org)?

**Comment by fbiville** [comment]
For the record, we managed to solve the issue by rewriting each Liquigraph change sets defining post-conditions with queries leveraging APOC (in that case: `apoc.nodes.delete` for batch node deletion), since APOC was already used for other migrations.
