### ISSUE TITLE
Liquibase docker img with plugin fails

### ISSUE THREAD

**Issue by rokjoana** [liquibase/liquibase-neo4j#341]
Currently I'm working on a project that is using neo4j and I am looking into using testcontainers for our test dependencies. 
Since we are using liquibase already, it would be useful to have a docker image extended from the original liquibase docker image. Unfortunately I tried with the following 
```
FROM liquibase/liquibase:4.19

USER root
WORKDIR /liquibase/internal/lib/
RUN curl -o liquibase-neo4j.jar https://repo1.maven.org/maven2/org/liquibase/ext/liquibase-neo4j/4.20.0/liquibase-neo4j-4.20.0-full.jar
RUN chown liquibase: liquibase-neo4j.jar
WORKDIR /liquibase
USER liquibase
```
But the execution of liquibase fails with
```
Unexpected error running Liquibase: Driver class was not specified and could not be determined from the url (jdbc:neo4j:bolt://localhost:54225)
```

I suspect the plugin is not correctly being supported in the docker image. I'm afraid that the support for plugins is not the best on the official docker image but I don't know if anyone has any more knowledge on this.

**Comment by fbiville** [comment]
Hello, can you provide more details on your setup?
How do configure Liquibase?

**Comment by rokjoana** [comment]
sorry, I found out the problem is more closely related with the liquibase docker image not recognizing properly the plugin jar. I've commented on an open issue there and I'm awaiting some solution

**Comment by rokjoana** [comment]
Depends on https://github.com/liquibase/docker/issues/177
