### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [liquibase/liquibase-neo4j#352]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by fbiville** [comment]
Now enabled, thanks @igibek!

**Comment by fbiville** [comment]
@igibek I don't think I received anything yet?

**Comment by fbiville** [comment]
Closing this as I have not received any security advisory.
Feel free to re-open @igibek if there is still something to do.
