### ISSUE TITLE
Execution for Oracle getting Neo4J error

### ISSUE THREAD

**Issue by doakd** [liquibase/liquibase-neo4j#413]
### Search first

- [X] I searched and no similar issues were found

### Description

Running a Liquibase CLI against an Oracle database.  Hundreds of changesets.  Getting error:

"computed values are currently not supported by the Neo4j plugin"

No indication in the log of which changeset is the issue.

### Steps To Reproduce

run Liquibase update or status or validate

### Expected/Desired Behavior

Changelogs are executed in Oracle database target

### Liquibase Version

4.21.1

### Database Vendor & Version

Oracle 19c

### Liquibase Integration

CLI

### Liquibase Extensions

liquibase-neo4j liquibase-teradata

### OS and/or Infrastructure Type/Provider

linux

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by fbiville** [comment]
@doakd https://github.com/liquibase/liquibase-neo4j/releases/tag/liquibase-neo4j-4.22.0.2 is out and should fix the issue you were facing.
