### ISSUE TITLE
Liquibase has removed their v4.22 release

### ISSUE THREAD

**Issue by majensen** [liquibase/liquibase-neo4j#422]
I'm sure the team already knows this, but it appears Liquibase has made the entire v4.22 release series unavailable.
https://github.com/liquibase/liquibase/releases/tag/v4.22.0
Just a heads-up.

**Comment by fbiville** [comment]
I see, the extension also cannot work with 4.23.0 as it stands, I'm waiting for the release of 4.23.1.
If you really need Liquibase 4.22, it's still available [here](https://repo1.maven.org/maven2/org/liquibase/liquibase-core/4.22.0/).

**Comment by fbiville** [comment]
The extension also cannot work with 4.23.0 as it stands, I'm waiting for the release of 4.23.1.

**Comment by majensen** [comment]
Sounds good- I just went to v21 and it is all good. Just wanted to inform.

**Comment by majensen** [comment]
Maybe so- I found 4.22 of the ext did not work in v4.23 of LB. I didn't explore the problem, though, finding that v4.21 of both did work together.Sent from my iPhoneOn Jul 11, 2023, at 6:17 AM, Florent Biville ***@***.***> wrote:﻿
Thank you, I'm wondering whether I should remove the 4.22.x releases of the extension as well.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***
 hub.com>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/liquibase/liquibase-neo4j/issues/422#issuecomment-1630557023",
"url": "https://github.com/liquibase/liquibase-neo4j/issues/422#issuecomment-1630557023",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]-- 
This message has been scanned for viruses and
dangerous content by
MailScanner, and is
believed to be clean.


-- 
This message has been scanned for viruses and
dangerous content by
MailScanner, and is
believed to be clean.

**Comment by fbiville** [comment]
Yes, Liquibase core 4.23.0 introduced some breaking changes that are quite challenging to incorporate as-is in the extension. Until 4.32.1 is release, I'd advise to stick with Liquibase core 4.21.x (and the latest Neo4j extension version probably works here).
