### ISSUE TITLE
Minor change to tutorial

### ISSUE THREAD

**Issue by molivasdat** [liquibase/liquibase-neo4j#5]
Hi @fbiville 
I was able to build once moving to java 11.  Thanks for the tip.
One minor change you might make for those that are more familiar with Liquibase and not so much neo4j is to put a link to get to the neo4j interface to see the change with the assumption that it is running locally and where to click to view the entry that was just created.

For instance
```
Let us look at the database and check whether the Movie node has been created:
```
If you are running locally it would be found here
http://localhost:7474/browser/
Login and Click Database -> Node Labels -> Movie

Or something similar

**Comment by fbiville** [comment]
Thanks, that's a very good idea. Let me do add that.

**Comment by fbiville** [comment]
@molivasdat let me know what you think of https://github.com/liquibase/liquibase-neo4j/pull/6
