### ISSUE TITLE
How are __LiquibaseChangeLog nodes suppose to be created?

### ISSUE THREAD

**Issue by e1cryank** [liquibase/liquibase-neo4j#96]
Hi, I currently have a couple of changelogs in this folder structure

```
changelogs
 |_ changelogs-0000.xml
 |_ changelogs-0010.xml
 |_ ...
changelog-master.xml
```
The master changelog has `<includeAll path="changelogs/" relativeToChangelogFile="true"/>` in it. After I run liquibase, I see only one `__LiquibaseChangeLog` node - I expected a node for each xml file in the changelogs folder.

Is this a bug or expected outcome?

**Comment by fbiville** [comment]
Conceptually, you can spread change **sets** over several files, but there is only ever a single entry point (this is what `__LiquibaseChangeLog` represents). The plugin does not persist intermediate change log files as nodes.

`__LiquibaseChangeSet` nodes are linked the main change log node and they each refer to their enclosing file via their path attributes.

Does that help?

**Comment by fbiville** [comment]
Closing this, as the history graph structure is internal. Happy to provide more explanation if needed, but whatever information I provide is not guaranteed to remain true over time.
